Homework1
cecelia-tech/csHomework pull request #1
Opened 2021-12-06 09:50 UTC by cecelia-tech

Submitting homework 1 tasks 1-3.

2021-12-06 11:13 UTC, radislavkireev requested changes

2021-12-06 11:13 UTC, radislavkireev commented on Homework1/ISBN/Isbn.cs
> +    class Isbn
add protection modifier explicitly: "internal"

2021-12-06 11:13 UTC, radislavkireev commented on Homework1/ISBN/Isbn.cs
> +        public void Print(string isbnCode)
This method is not required, drop it

2021-12-06 11:13 UTC, radislavkireev commented on Homework1/ISBN/Isbn.cs
> +        public void IsbnNumericCode(string userInput)
The methods names does not correspond to what they actually do. 
1 . Method name should start with verb what describes the action it does. 
2. Method code should do what it name declares. So, if it is called GetSomething it should return some value, but not print it or save for example. 

Lets update the class next way:
1.public void IsbnNumericCode(string userInput) -> rename to public string  GetIsbnNumericCode(string userInput). The method should NOT print numeric code, leave it for Program.cs, it should only return ISBN number. 

2. public string StringToIntArrayConvertor(string numbersInString) -> rename to public int[] ConvertStringToIntArray(string numbersInString). The method should NOT call MultiplicationOfNumbers, it should return 
arrayOfNum.

3. public string MultiplicationOfNumbers(int[] arrayOfNumbers) => rename to public int SumAndMultiplyNumbers(int[] arrayOfNumbers) . The method should NOT call CheckDigit, but return sumOfMultipliedNumbers. 

4. Update GetIsbnNumericCode, so it calls methods in the following order: 
```
{
    string finalIsbn = "ISBN ";
    //....
    var arrayOfNum= ConvertStringToIntArray(userInput);
    int sumOfMultipliedNumbers= SumAndMultiplyNumbers(arrayOfNum);
   string checkDigit = CheckDigit(sumOfMultipliedNumbers);
  
    return finalIsbn + checkDigit;
 
}
```

2021-12-06 11:13 UTC, radislavkireev commented on Homework1/SumOfArray/SumBetweenNumbers.cs
> +        public void SumOfRequaredNumbers(string userInputNumbers)
rename to PrintSumOfRequiredNumbers

2021-12-06 11:13 UTC, radislavkireev commented on Homework1/SumOfArray/SumBetweenNumbers.cs
> +        public void Print(int sumOfPartOfArray)
This method is not required, just call Console.WriteLine at the caller.

2021-12-06 11:13 UTC, radislavkireev commented on Homework1/SumOfArray/SumBetweenNumbers.cs
> +    class SumBetweenNumbers
add internal

2021-12-06 11:13 UTC, radislavkireev commented on Homework1/SumOfArray/SumBetweenNumbers.cs
> +        public int[] StringToInt(string userInpput)
rename method, so it starts with a verb

2021-12-06 11:13 UTC, radislavkireev commented on Homework1/SumOfArray/SumBetweenNumbers.cs
> +        public int MaxValueIndex(int[] userInputNumbers)
rename method, so it starts with a verb

2021-12-06 11:13 UTC, radislavkireev commented on Homework1/SumOfArray/SumBetweenNumbers.cs
> +        public int MinValueIndex(int[] userInputNumbers)
rename method, so it starts with a verb

2021-12-06 11:13 UTC, radislavkireev commented on Homework1/Ternary/TernaryConvertor.cs
> +        public void NumberPrint(int number)
Drop this method, just call Console.WriteLine

2021-12-06 11:13 UTC, radislavkireev commented on Homework1/Ternary/TernaryConvertor.cs
> +        public void CheckForAppropriateInteger(int numberFrom, int numberTo)
Rename to PrintNumberWith2Twos

2021-12-06 11:13 UTC, radislavkireev commented on Homework1/Ternary/TernaryConvertor.cs
> +        public StringBuilder ConvertToTernary(int number)
This method does not work correctly. 
The alg could be viewed at https://www.geeksforgeeks.org/ternary-number-system-or-base-3-numbers/ as an example. 

Here is the output for range 0..30.
As you can see it starts from 10, when should from 01. 
Also, it repeats ternary representations twice. 

10
11
12
10
11
12
10
11
12
100
101
102
110
111
112
120
121
122
100
101
102
110
111
112
120
121
122
1000
1001
1002
1010

2021-12-09 10:43 UTC, rkireevLT approved these changes

2021-12-09 10:45 UTC, radislavkireev approved these changes

2021-12-09 10:45 UTC, merged